# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e81vgC0e9UArQgR9MQO8fJY3_XeQyRXo

"""

# pipでインストールをする事
# !pip install scikit-learn

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pickle

# csvを読み込む
df = pd.read_csv('pointData.csv')


# トレーニングデータ作成
X = df.loc[:, 'point_0_x' : 'point_20_z']
y = df['characterType']


# トレーニング用とテスト用で、データを8:2に分ける
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=0
)

# ランダムフォレストで学習
clf = RandomForestClassifier(random_state=0)
clf.fit(X_train, y_train)

# 予測と結果
pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, pred)

print(accuracy) 
# 0.9426229508196722

# ファイル保存
filename = 'learning_model.sav'
pickle.dump(clf, open(filename, 'wb'))